version: "3.9"

services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=jetstyletaskdb

  redis:
    image: redis
    restart: always

  app:
    restart: always
    build:
      context: ../Fibonacci-Sequence-API
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    command: ["python", "./testtask/manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  worker:
    restart: always
    build:
      context: ../Fibonacci-Sequence-API
    command: ['celery', '--workdir=./testtask', '-A', 'config', 'worker' ]

volumes:
  postgres_data: